# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: emiyaconsulting
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todo-rest-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-rest-api

plugins:
    - serverless-offline

provider:
    name: aws
    region: us-west-2
    stage: "dev"
    runtime: nodejs22.x
    memorySize: 128
    timeout: 3

functions:
    getItems:
        handler: src/handlers/getItems.handler
        description: Get all items
        events:
            - http:
                  path: /items
                  method: get

    createItem:
        handler: src/handlers/createItem.handler
        description: Create a single item
        events:
            - http:
                  path: /item
                  method: post

    updateItem:
        handler: src/handlers/updateItem.handler
        description: Update a single item
        events:
            - http:
                  path: /item
                  method: patch

    getItemById:
        handler: src/handlers/getItemById.handler
        description: Get a single item by ID
        events:
            - http:
                  path: /item/{id}
                  method: get

    deleteItem:
        handler: src/handlers/deleteItem.handler
        description: Flag a single item as deleted
        events:
            - http:
                  path: /item
                  method: delete