# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: emiyaconsulting
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todo-rest-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-rest-api

plugins:
    - serverless-offline

provider:
    name: aws
    stage: ${opt:stage}
    region: us-west-2
    runtime: nodejs22.x
    timeout: 30
    environment:
        STAGE: ${self:provider.stage}

functions:
    api:
        handler: ./src/index.handler
        events:
            - httpApi: "*"
        environment:
            PORT: 3000
            SECRET_NAME: todo-rest-api-mong
            AWS_PROFILE: EmiyaDevsProd-880923331368

package:
    patterns:
        - src/**
