# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: emiyaconsulting
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todo-rest-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-rest-api

plugins:
    - serverless-dynamodb
    - serverless-offline

custom:
    serverless-dynamodb:
        start:
            port: 8000
            docker: false

provider:
    name: aws
    region: us-west-2
    stage: "dev"
    runtime: nodejs22.x
    memorySize: 128
    timeout: 30
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
          Resource:
              - arn:aws:dynamodb:us-west-2:{ID}:table/Item

functions:
    app:
        handler: dist/src/index.handler
        events:
            - httpApi:
                  path: /
                  method: GET
    getItems:
        handler: dist/src/index.handler
        description: Get all items
        events:
            - httpApi:
                  path: /items
                  method: GET
    createItem:
        handler: dist/src/index.handler
        description: Create a single item
        events:
            - httpApi:
                  path: /item
                  method: POST
    updateItem:
        handler: dist/src/index.handler
        description: Update a single item
        events:
            - httpApi:
                  path: /item
                  method: PATCH
    getItemById:
        handler: dist/src/index.handler
        description: Get a single item by ID
        events:
            - httpApi:
                  path: /item/{id}
                  method: GET
    deleteItem:
        handler: dist/src/index.handler
        description: Flag a single item as deleted
        events:
            - httpApi:
                  path: /item/{id}
                  method: DELETE

resources:
    Resources:
        Item:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: Item
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
